### ISSUE TITLE
Create data flow diagram for Sensor Device and Data Acquisition Server

### ISSUE THREAD

**Issue by kovacszoli** [ionutmnere/Self-Adjusting-Sensor-Network#39]

**Comment by ionutmnere** [comment]
1. --> devices.jpg 
 - Please update the device diagram ("devices.jpg") with a label for the router device. Also would be an idea to have another diagram similar with this one where RPi plays the router role. Will be useful for the presentation section "Future improvements".

2. --> flowchart.png
 [GUI section]:
           -  "Incoming data from user" maybe would be more clear to say "Request from user"
[NodeJS server section]:
           - A conditional block should have one input and at least two outputs (See conditional block "Is data correct").
[Ppi section]: 
            - "MQtt data senser/receiver" block should have another connection for "receive" part, like "REST data sender/receiver" block has.
[SensorDevice section]:
           - The block "Add data to the Json which will be sent" is not very clear. If is creating and sending JSon object, please state it like that.
           - We are not handling interrupts from sensors (at least so far :D ); therefore block 
              "Incoming data from sensor" maybe would be more clear to be "Read data from 
               sensors."
            - I would say "Is data valid" is a more common expression used, instead of "Is data correct". What do you say?
