### ISSUE TITLE
Create presentation

### ISSUE THREAD

**Issue by FleischmanRaul** [ionutmnere/Self-Adjusting-Sensor-Network#48]
Good looking and interesting

**Comment by ionutmnere** [comment]
Review - round 1
 1 - Slides 2, 3, 4 and 5 - Would be more suggestive if we had a visible title
 2 - Slide 6 - Starts with the solution already. As I said yesterday, would be nice if we present at first a concept diagram - look at the PPT I've sent you at the beginning (about 5 weeks ago). 
 3 - Also the title should be more general as the implemented solution is more general.
 4 - Slide 7 - Does not have a title
 5 - Between 7 and 8 would be better to have the "Q&A" slide.
6 - Demo slide will be the last one as we do not turn back to presentation after the demo
7  - All slides --> slide number should be in "x/y" format where x is the current slide number and y is the total number of slides.
